include("shared.lua")
net.Receive("lot_menu", function()
	local owner = net.ReadEntity()
	local owners = net.ReadTable()
	print(owner)
	PrintTable(owners)
	local frame = vgui.Create("DFrame")
	frame:SetTitle("Lot Menu")
	frame:SetSize(800, 600)
	frame:Center()
	frame:MakePopup(true)
	local cats = vgui.Create("DCollapsibleCategory", frame)
	cats:Dock(FILL)
	cats:SetLabel("Actions")
	local buy = vgui.Create("DButton", cats)
	if owner:IsPlayer() then
		buy:SetText("Sell this lot")
	else
		buy:SetText("Buy this lot")
	end
	buy:Dock(TOP)
	buy.DoClick = function()
		net.Start("lot_buy")
		net.SendToServer()
		frame:Close()
	end
end)